[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.clangd]
command = "clangd"

[language-server.tombi]
command = "tombi"

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
config = {  }

[language-server.ruff]
command = "uv"
args = ["run", "ruff", "server"]

[[language]]
name = "c"
auto-format = false
language-servers = ["clangd"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi"]

[[language]]
name = "markdown"
rulers = [80]

[[language]]
name = "rust"
rulers = [100]
auto-format = false

[[language]]
name = "python"
scope = "source.python"
language-servers = ["ty"]
auto-format = false
injection-regex = "python"
file-types = ["py", "pyi", ".pythonrc"]
roots = ["setup.py", "setup.cfg", "pyproject.toml", "."]
comment-token = "#"

[language.formatter]
command = "uv"
args = ["run", "ruff", "format", "-q", "-"]

[language.indent]
tab-width = 4
unit = "    "
